/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // SDK
  sdkSidebar: [{type: 'autogenerated', dirName: 'sdk'}],

  // User Manual
  userManualSidebar: [{type: 'autogenerated', dirName: 'manual'}],
};

export default sidebars;
